server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: booking-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/bookings}
    username: ${SPRING_DATASOURCE_USERNAME:justlife}
    password: ${SPRING_DATASOURCE_PASSWORD:justlife}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
    repositories:
      enabled: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

justlife:
  kafka:
    enabled: true
    topics:
      booking-events: booking.events
      booking-events-dlt: booking.events.dlt


# SWAGGER
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  override-with-generic-response: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE:http://localhost:8761/eureka/}

resilience4j:
  circuitbreaker:
    instances:
      professionals:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
